CREATE USER AD_TEMA02 IDENTIFIED BY AD_TEMA02;
GRANT DBA TO AD_TEMA02;

ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY';
--ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';

CREATE TABLE ALUMNOS(
 cCodAlu VARCHAR2(6) CONSTRAINT PK_ALUMNOS PRIMARY KEY,
 cNomAlu VARCHAR2(100) NOT NULL
);

CREATE TABLE CURSOS(
 cCodCurso VARCHAR2(6) CONSTRAINT PK_CURSOS PRIMARY KEY,
 cNomCurso VARCHAR2(100) NOT NULL,
 nNumExa NUMBER(3) DEFAULT 1 NOT NULL
);

CREATE TABLE MATRICULAS(
 cCodAlu VARCHAR2(6) NOT NULL,
 cCodCurso VARCHAR2(6) NOT NULL,
 nNotaMedia NUMBER(3) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_MATRICULAS PRIMARY KEY (cCodAlu,cCodCurso)
);

ALTER TABLE MATRICULAS ADD CONSTRAINT FK_MATRICULAS_ALUMNO FOREIGN KEY (cCodAlu)REFERENCES ALUMNOS(cCodAlu);
ALTER TABLE MATRICULAS ADD CONSTRAINT FK_MATRICULAS_CURSOS FOREIGN KEY (cCodCurso)REFERENCES CURSOS(cCodCurso);

CREATE TABLE EXAMENES(
 cCodAlu VARCHAR2(6) NOT NULL,
 cCodCurso VARCHAR2(6) NOT NULL,
 nNumExam NUMBER(3) DEFAULT 1 NOT NULL,
 dFecExam DATE,
 nNotaExam NUMBER(6,2) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_EXAMENES PRIMARY KEY (cCodAlu,cCodCurso,nNumExam)
);

ALTER TABLE EXAMENES ADD CONSTRAINT FK_EXAMENES_MATR FOREIGN KEY (cCodAlu,cCodCurso)REFERENCES MATRICULAS(cCodAlu,cCodCurso);

CREATE OR REPLACE TRIGGER tr_Examenes_Upd
AFTER UPDATE ON EXAMENES FOR EACH ROW    
declare 
    difNota NUMBER(10,2) := 0;
    nExa NUMBER(10,0) := 0;
BEGIN
    difNota := :new.nNotaExam - :old.nNotaExam; 
    SELECT nNumExa INTO nExa FROM CURSOS WHERE cCodCurso = :new.cCodCurso;
    UPDATE MATRICULAS SET nNotaMedia = nNotaMedia + (difNota / nExa) WHERE cCodAlu = :new.cCodAlu AND cCodCurso = :new.cCodCurso;
END;

INSERT INTO ALUMNOS VALUES ('001','Antonio');
INSERT INTO ALUMNOS VALUES ('002','Maria');
INSERT INTO CURSOS VALUES ('I001','Ingles Basico',5);
INSERT INTO CURSOS VALUES ('I002','Ingles Intermedio',8);
INSERT INTO CURSOS VALUES ('I003','Ingles Avanzado',10);
INSERT INTO CURSOS VALUES ('F001','Frances Basico',3);
INSERT INTO CURSOS VALUES ('C002','Chino Intermedio',9);
COMMIT;

CREATE OR REPLACE PROCEDURE sp_AltaMatricula (xcCodAlu VARCHAR2, xcCodCurso VARCHAR2, xError OUT NUMBER) IS 
    nExa NUMBER (10, 2) := 0;
    i NUMBER := 1;
BEGIN
    SELECT nNumExa INTO nExa FROM CURSOS WHERE xcCodCurso = cCodCurso;
    
    INSERT INTO MATRICULAS VALUES (xcCodAlu, xcCodCurso, 0);
    FOR i  IN 1..nExa LOOP
        INSERT INTO EXAMENES VALUES (xcCodAlu,xcCodcurso, i, NULL, 0);
    END LOOP;
    xError := nExa;
EXCEPTION
 WHEN OTHERS THEN xError := -1;
END;

COMMIT;
SELECT SYSDATE FROM DUAL;

SELECT nNumExam, dFecExam, nNotaExam FROM EXAMENES WHERE cCodAlu = 003  AND cCodCurso = 'AD';

CREATE OR REPLACE VIEW  vista_tabla_matriculas AS
    SELECT a.cCodAlu, a.cNomAlu, c.cCodCurso, c.cNomCurso, m.nNotaMedia
    FROM ALUMNOS a, CURSOS c, MATRICULAS m 
    WHERE a.cCodAlu = m.cCodAlu AND c.cCodCurso = m.cCodCurso
    ORDER BY a.cCodAlu ASC;

INSERT INTO ALUMNOS VALUES ('003','Wence');
INSERT INTO CURSOS VALUES ('AD','ACCESO',3);
INSERT INTO ALUMNOS VALUES ('004','Alicia');

INSERT INTO MATRICULAS  VALUES ('003','AD',0);

INSERT INTO EXAMENES  VALUES ('003','AD',1,NULL,0);
INSERT INTO EXAMENES  VALUES ('003','AD',2,NULL,0);
INSERT INTO EXAMENES  VALUES ('003','AD',3,NULL,0);


SELECT * FROM ALUMNOS;
SELECT * FROM CURSOS;
SELECT * FROM MATRICULAS;
SELECT * FROM EXAMENES;
SELECT * FROM vista_tabla_matriculas;

SELECT * FROM vista_tabla_matriculas WHERE cCodAlu = '002';

SELECT * FROM EXAMENES WHERE cCodCurso = 'F001';

SELECT * FROM vista_tabla_matriculas WHERE cCodAlu = 003
SELECT nNumExam, dFecExam, nNotaExam FROM EXAMENES WHERE cCodAlu = 003 AND cCodCurso = 'F001';


UPDATE EXAMENES SET nNOTAExam = 6 WHERE nNumExam = 1;
UPDATE EXAMENES SET nNOTAExam = 8 WHERE nNumExam = 2;
UPDATE EXAMENES SET nNOTAExam = 5 WHERE nNumExam = 3;

UPDATE EXAMENES SET dFecExam = '12/12/2023', nNotaExam = 7.8 WHERE cCodAlu = 003 AND cCodCurso = 'AD'  AND nNumExam = 1;
COMMIT;